import { NextRequest, NextResponse } from 'next/server';
import { verifyWebhookSignature, isMergedPrEvent, type PullRequestMergedEvent } from '@/lib/evoguard/github-webhook';
import { generateDecisionId, parseDecisionId } from '@/lib/evoguard/uuidv7';
import { createCommitStatus, createPullRequestComment } from '@/lib/evoguard/github-api';
import { db } from '@/lib/db';

function buildStampComment(
  decisionId: string,
  timestamp: string,
  prNumber: number,
  mergeSha: string,
  authorLogin: string
): string {
  const bt = '`';
  const code = bt + bt + bt;
  return [
    '## ⚡ EvoGuard Decision ID Stamp',
    '',
    '| Field | Value |',
    '|-------|-------|',
    `| **Decision ID** | ${code}${decisionId}${code} |`,
    `| **Timestamp** | ${timestamp} |`,
    `| **PR** | #${prNumber} |`,
    `| **Merge Commit** | ${code}${mergeSha}${code} |`,
    `| **Author** | @${authorLogin} |`,
    '',
    '> This decision record was automatically generated by [EvoGuard](https://github.com/modarresi1913/Evoguard).',
  ].join('\n');
}

export async function POST(req: NextRequest) {
  // --- 1. Read raw body ---
  const rawBody = await req.text();

  // --- 2. Verify webhook signature ---
  const signature = req.headers.get('x-hub-signature-256');
  const webhookSecret = process.env.GITHUB_WEBHOOK_SECRET;

  if (!webhookSecret) {
    console.error('[EvoGuard] GITHUB_WEBHOOK_SECRET is not configured');
    return NextResponse.json(
      { error: 'Webhook secret not configured' },
      { status: 500 }
    );
  }

  if (!verifyWebhookSignature(rawBody, signature, webhookSecret)) {
    return NextResponse.json(
      { error: 'Invalid signature' },
      { status: 401 }
    );
  }

  // --- 3. Parse and validate event ---
  let parsed: unknown;
  try {
    parsed = JSON.parse(rawBody);
  } catch {
    return NextResponse.json(
      { error: 'Invalid JSON' },
      { status: 400 }
    );
  }

  if (!isMergedPrEvent(parsed)) {
    return NextResponse.json({ message: 'Event ignored', action: (parsed as Record<string, unknown>)?.action });
  }

  const event: PullRequestMergedEvent = parsed;
  const pr = event.pull_request;
  const repoFullName = event.repository.full_name;
  const mergeSha = pr.merge_commit_sha!;

  console.log(`[EvoGuard] PR #${pr.number} merged in ${repoFullName}, SHA: ${mergeSha}`);

  // --- 4. Generate Decision ID (UUID v7) ---
  const decisionId = generateDecisionId();
  const parsedId = parseDecisionId(decisionId);
  const timestamp = new Date(parsedId.timestamp);

  console.log(`[EvoGuard] Generated Decision ID: ${decisionId} (ts: ${timestamp.toISOString()})`);

  // --- 5. Stamp Decision ID via GitHub API ---
  const githubToken = process.env.GITHUB_TOKEN;
  const [owner, repo] = repoFullName.split('/');

  const stampComment = buildStampComment(
    decisionId,
    timestamp.toISOString(),
    pr.number,
    mergeSha,
    pr.user.login
  );
  const statusDescription = `Decision ID: ${decisionId.slice(0, 8)}...`;

  try {
    if (githubToken) {
      await createPullRequestComment({
        token: githubToken,
        owner,
        repo,
        prNumber: pr.number,
        body: stampComment,
      });
      console.log(`[EvoGuard] Comment posted to PR #${pr.number}`);

      await createCommitStatus({
        token: githubToken,
        owner,
        repo,
        sha: mergeSha,
        state: 'success',
        description: statusDescription,
        context: 'evoguard/decision-id',
      });
      console.log(`[EvoGuard] Commit status created for ${mergeSha}`);
    } else {
      console.warn('[EvoGuard] GITHUB_TOKEN not set — skipping GitHub API calls');
    }
  } catch (err) {
    console.error('[EvoGuard] GitHub API error:', err);
  }

  // --- 6. Persist DecisionRecord to database ---
  try {
    await db.decisionRecord.create({
      data: {
        decisionId,
        prNumber: pr.number,
        repoFullName,
        mergeCommitSha: mergeSha,
        author: pr.user.login,
        prTitle: pr.title,
        prBody: pr.body,
      },
    });
    console.log(`[EvoGuard] DecisionRecord persisted: ${decisionId}`);
  } catch (err) {
    console.error('[EvoGuard] Database error:', err);
    return NextResponse.json(
      { error: 'Failed to persist decision record' },
      { status: 500 }
    );
  }

  // --- 7. Respond ---
  return NextResponse.json({
    message: 'Decision ID stamped',
    decisionId,
    prNumber: pr.number,
    mergeCommitSha: mergeSha,
  });
}
